version: '3.4'
services:
  coffeapi:
    build: coffeapi/
    ports:
      - "8080:80"
    
    
  teaapi:
    build: teaapi/
    ports:
      - "8082:80"
  
  envoygateway:
    build: Envoy/
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
     
